# Generated by Django 2.0.13 on 2019-10-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rent', models.IntegerField()),
                ('area', models.IntegerField(default=None)),
                ('bedrooms', models.IntegerField(default=None)),
                ('parking', models.BooleanField(default=False)),
                ('img', models.ImageField(default=None, upload_to='images')),
                ('bathrooms', models.IntegerField(default=None)),
                ('description', models.TextField(default='House')),
                ('Owner', models.CharField(default='Human', max_length=100)),
                ('address', models.TextField(default='Earth')),
                ('ListedByOwner', models.BooleanField(default=True)),
                ('Type', models.CharField(default='Appartment', max_length=20)),
            ],
        ),
    ]
