# Generated by Django 2.2.3 on 2019-08-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rent', models.IntegerField()),
                ('area', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('img', models.ImageField(upload_to='pics')),
                ('bath', models.IntegerField()),
            ],
        ),
    ]
