# Generated by Django 2.2.3 on 2019-08-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190818_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='img',
            field=models.ImageField(upload_to='mysite/static/img'),
        ),
    ]
