# Generated by Django 2.2.3 on 2019-08-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190818_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='img',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
