# Generated by Django 2.2.3 on 2019-08-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20190818_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
