# Generated by Django 2.2.3 on 2019-08-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20190820_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='img',
            field=models.ImageField(upload_to='static'),
        ),
    ]
