# Generated by Django 2.2.3 on 2019-08-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20190820_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='bath',
        ),
        migrations.RemoveField(
            model_name='house',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='house',
            name='garage',
        ),
        migrations.AddField(
            model_name='house',
            name='ListedByOwner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='house',
            name='Owner',
            field=models.CharField(default='Human', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='Type',
            field=models.CharField(default='Appartment', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.TextField(default='Earth'),
        ),
        migrations.AddField(
            model_name='house',
            name='bathrooms',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='house',
            name='bedrooms',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(default='House'),
        ),
        migrations.AddField(
            model_name='house',
            name='img2',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='house',
            name='img3',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='house',
            name='parking',
            field=models.BooleanField(default=False),
        ),
    ]
