# Generated by Django 2.2.3 on 2019-08-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20190823_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
    ]
