# Generated by Django 2.2.3 on 2019-08-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20190823_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='bathrooms',
            new_name='bath',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='bedrooms',
            new_name='bed',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='parking',
            new_name='garage',
        ),
    ]
