# Generated by Django 2.2.3 on 2019-08-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20190823_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='ListedByOwner',
        ),
        migrations.RemoveField(
            model_name='house',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='house',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='house',
            name='address',
        ),
        migrations.RemoveField(
            model_name='house',
            name='description',
        ),
        migrations.RemoveField(
            model_name='house',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='house',
            name='img3',
        ),
        migrations.AlterField(
            model_name='house',
            name='bath',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='bed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='garage',
            field=models.IntegerField(),
        ),
    ]
