# Generated by Django 2.2.3 on 2019-08-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20190823_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='bed',
            new_name='beds',
        ),
    ]
