# Generated by Django 2.2.3 on 2019-09-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_auto_20190823_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='house',
            name='img',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
