# Generated by Django 2.2.3 on 2019-09-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_house_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='house',
            name='img3',
        ),
    ]
